import pangolin2Metadata from "./pangolin2Metadata";
import pangolinMetadata from "./pangolinMetadata";
import pangoroMetadata from "./pangoroMetadata";
import crabMetadata from "./crabMetadata";
import darwiniaMetadata from "./darwiniaMetadata";
export const pangolin2MetaStatic = pangolin2Metadata;
export const pangolinMetaStatic = pangolinMetadata;
export const pangoroMetaStatic = pangoroMetadata;
export const crabMetaStatic = crabMetadata;
export const darwiniaMetaStatic = darwiniaMetadata;
